### ISSUE TITLE
Tile.getCreature(int i) függvény komment alapján nem egyértelmű funkcionalitású

### ISSUE THREAD

**Issue by szinyeribence** [BME-MIT-IET/iet-hf2021-sumatra-csak-jobb#6]
Tesztelés során találtam egy a Tile.getCreature függvényt, aminek a kommentje többértelmű. Így nem tudom, hogy jól van-e implementálva.

![image](https://user-images.githubusercontent.com/44683763/116921167-eb026d80-ac53-11eb-95b9-59d6927fc1a8.png)

Az itt a bajom, hogy a Creature-nek is van indexe. És nem tudom értelmezni, hogy a listában lévő index a kérdés, vagy hogy adott indexű creature-t keresünk. Szerintem a kódoló sem biztos, hogy tudta, mi a helyzet. 

![image](https://user-images.githubusercontent.com/44683763/116921288-138a6780-ac54-11eb-8fe0-26ffbc3aacff.png)

**Comment by attilakillin** [comment]
Hivatkozott részek, hogy könnyen el lehesse érni őket: [Tile](https://github.com/BME-MIT-IET/iet-hf2021-sumatra-csak-jobb/blob/75db53229f030d0e249709dc978abe8b464101d0/src/main/sumatra/Tile.java#L135), [Creature](https://github.com/BME-MIT-IET/iet-hf2021-sumatra-csak-jobb/blob/75db53229f030d0e249709dc978abe8b464101d0/src/main/sumatra/Creature.java#L27).

Megnéztem, az egyedüli hivatkozás a getCreature()-re az a [CreatureView](https://github.com/BME-MIT-IET/iet-hf2021-sumatra-csak-jobb/blob/75db53229f030d0e249709dc978abe8b464101d0/src/main/graphics/CreatureView.java#L46)ben van, ami azt a verziót igényli, amit a kód ír. Tippre a dokumentációt nem ugyanaz írta, mint a kódot, és ez okozza a gondot.

A Creature-ben az index az *tényleg* a globális index, az a printelésnél használatos egyedül, lásd a [listGameInfo](https://github.com/BME-MIT-IET/iet-hf2021-sumatra-csak-jobb/blob/75db53229f030d0e249709dc978abe8b464101d0/src/main/sumatra/Creature.java#L93) függvényt.

Tehát a dokumentáció javítása orvosolná is a gondot, nem bugos a kód :P Csak nem is igazán nevezhető clean code-nak.

**Comment by szinyeribence** [comment]
Akkor szerintem átírom a kommentet, hogy értelmezhető legyen a dolog. De am még vannak helyek, ahol a komment elnagyolt.

**Comment by szinyeribence** [comment]
![image](https://user-images.githubusercontent.com/44683763/117224335-f4383980-ae0f-11eb-9c53-4a552f092bcf.png)

Szerintem ez így jobb lesz
