### ISSUE TITLE
Tile.GetNeighbors() kell copy?

### ISSUE THREAD

**Issue by szinyeribence** [BME-MIT-IET/iet-hf2021-sumatra-csak-jobb#7]
![image](https://user-images.githubusercontent.com/44683763/117139181-3d56a200-adac-11eb-940c-baf09ffe00fc.png)

Itt van ez a kódrészlet a Tile osztályból. Szerintem itt a neighbors lista shallow copy változatát kéne visszaadni, nem a konkrét lista objektumot.

Ti mit gondoltok erről?

**Comment by attilakillin** [comment]
Attól függ, mi a célunk. Megnéztem a használatokat, mindenhol csak olvassák a listát, sehol sem módosítják, így fölösleges mindig egy-egy másolatot létrehozni. Ugyanakkor a veszély fenn áll, hogy valaki mégis módosítja, hiszen semmi nem jelöli azt, hogy ez egy olyan lista, amit nem kéne módosítani.

Java-ban van arra mód, hogy egy immutable interfészen keresztül adjuk vissza a listát? Mint Kotlinban a `List` a `MutableList` helyett?

**Comment by szinyeribence** [comment]
![image](https://user-images.githubusercontent.com/44683763/118376274-568afa00-b5c7-11eb-9b0f-6ccaf78dc167.png)


Nem változtattam a függvényen, nem tettem immutable objektummá sem. A kommentbe írtam figyelmeztetést.
